coingecko:
  vs_currency: "usd"
  coin_ids: ["bitcoin", "ethereum"]
  days: 30
paths:
  db: "data/warehouse.db"
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  dashboards_dir: "data/dashboards"
logging:
  file: "logs/pipeline.log"
supplementary_datasets:
  - id: "portfolio"
    type: "csv"
    path: "data/processed/sample_portfolio.csv"
